import { buildTrie } from "./trie";

const medicationList = [
  "Abilify",
  "Abilify Maintena",
  "Abiraterone",
  "Acetaminophen",
  "Acetylcysteine",
  "Actemra",
  "Actos",
  "Acyclovir",
  "Adderall",
  "Adderall XR",
  "Advair Diskus",
  "Advil",
  "Afinitor",
  "Aimovig",
  "Ajovy",
  "Albuterol",
  "Aldactone",
  "Alecensa",
  "Alendronate",
  "Aleve",
  "Alfuzosin",
  "Allegra",
  "Allopurinol",
  "Alprazolam",
  "Alunbrig",
  "Amantadine",
  "Ambien",
  "Ambroxol",
  "Amiodarone",
  "Amitriptyline",
  "Amlodipine",
  "Amoxicillin",
  "Amoxicillin and Clavulanate",
  "Ampicillin",
  "Anastrozole",
  "AndroGel",
  "Annovera",
  "Apalutamide",
  "Apixaban",
  "Apokyn",
  "Apriso",
  "Aptiom",
  "Aricept",
  "Arikayce",
  "Arimidex",
  "Aripiprazole",
  "Aristada",
  "Aromasin",
  "Ascorbic acid",
  "Aspirin",
  "Atarax",
  "Atenolol",
  "Ativan",
  "Atogepant",
  "Atomoxetine",
  "Atorvastatin",
  "Aubagio",
  "Augmentin",
  "Austedo",
  "Auvelity",
  "Avsola",
  "Azathioprine",
  "Azelastine",
  "Azilect",
  "Azithromycin",
  "Azulfidine",
  "Bacitracin",
  "Baclofen",
  "Bactrim",
  "Bactrim DS",
  "Bactroban",
  "Balsalazide",
  "Banzel",
  "Baqsimi",
  "Basaglar",
  "Bavencio",
  "Belbuca",
  "Belsomra",
  "Benadryl",
  "Benazepril",
  "Bendeka",
  "Benicar",
  "Benlysta",
  "Bentyl",
  "Benzonatate",
  "Benztropine",
  "Berinert",
  "Betadine",
  "Betamethasone",
  "Bicalutamide",
  "Biktarvy",
  "Biotin",
  "Bisacodyl",
  "Bismuth subsalicylate",
  "Bisoprolol",
  "Black Cohosh",
  "Blincyto",
  "Boniva",
  "Botox",
  "Breo Ellipta",
  "Breyanzi",
  "Breztri Aerosphere",
  "Brilinta",
  "Brimonidine",
  "Briviact",
  "Bromfed DM",
  "Brukinsa",
  "Bryhali",
  "Budesonide",
  "Budesonide and formoterol",
  "Bumetanide",
  "Bumex",
  "Bunavail",
  "Buprenex",
  "Buprenorphine",
  "Buprenorphine & Naloxone",
  "Buprenorphine/naloxone",
  "Bupropion",
  "Buspar",
  "Buspirone",
  "Bystolic",
  "Cabenuva",
  "Cabometyx",
  "Calcitriol",
  "Calcium carbonate",
  "Calquence",
  "Canasa",
  "Caplyta",
  "Captopril",
  "Carbamazepine",
  "Carbidopa and levodopa",
  "Carvedilol",
  "Carvykti",
  "Casodex",
  "Cefadroxil",
  "Cefdinir",
  "Cefixime",
  "Ceftriaxone",
  "Cefuroxime",
  "Celebrex",
  "Celecoxib",
  "Celexa",
  "Cephalexin",
  "Cequa",
  "Cetirizine",
  "Chlorthalidone",
  "Cholecalciferol",
  "Cialis",
  "Cimzia",
  "Cinryze",
  "Cipro",
  "Ciprofloxacin",
  "Cisplatin",
  "Citalopram",
  "Clarithromycin",
  "Claritin",
  "Clindamycin",
  "Clobetasol",
  "Clobex",
  "Clodan",
  "Clonazepam",
  "Clonidine",
  "Clopidogrel",
  "Clotrimazole",
  "Codeine",
  "Colace",
  "Colazal",
  "Colchicine",
  "Concerta",
  "Coreg",
  "Cosentyx",
  "Coumadin",
  "Crestor",
  "Cyanocobalamin",
  "Cyclobenzaprine",
  "Cymbalta",
  "Dapagliflozin",
  "Darzalex",
  "Dayvigo",
  "Decadron",
  "Degarelix",
  "Delzicol",
  "Demerol",
  "Denosumab",
  "Depakote",
  "Depo-Provera",
  "Descovy",
  "Desloratadine",
  "Desvenlafaxine",
  "Desyrel",
  "Detrol",
  "Dexamethasone",
  "Dexilant",
  "Dextroamphetamine",
  "Dextromethorphan",
  "Dextrose",
  "Diacomit",
  "Diastat",
  "Diazepam",
  "Diclofenac",
  "Dicyclomine",
  "Diflucan",
  "Digoxin",
  "Dilantin",
  "Dilaudid",
  "Diltiazem",
  "Diovan",
  "Dipentum",
  "Diphenhydramine",
  "Diprolene",
  "Divalproex",
  "Divalproex sodium",
  "Docusate Sodium",
  "Donepezil",
  "Dopamine",
  "Doxazosin",
  "Doxepin",
  "Doxycycline",
  "Doxycycline Hyclate",
  "Dulaglutide",
  "Dulcolax",
  "Duloxetine",
  "Duopa",
  "Dupixent",
  "Dutasteride",
  "Echinacea",
  "Ecotrin",
  "Effexor",
  "Effexor XR",
  "Elagolix",
  "Elavil",
  "Eligard",
  "Eliquis",
  "Emgality",
  "Empagliflozin",
  "Empaveli",
  "Enalapril",
  "Enbrel",
  "Enhertu",
  "Enoxaparin",
  "Entecavir",
  "Entresto",
  "Entyvio",
  "Enzalutamide",
  "Epclusa",
  "Epidiolex",
  "Epinephrine",
  "EpiPen",
  "Eplerenone",
  "Epoetin alfa",
  "Ergocalciferol",
  "Erleada",
  "Ertapenem",
  "Erythromycin",
  "Erythromycin ophthalmic",
  "Escitalopram",
  "Esomeprazole",
  "Estrace",
  "Estradiol",
  "Eszopiclone",
  "Etanercept",
  "Ethambutol",
  "Etodolac",
  "Eulexin",
  "Euthyrox",
  "Evenity",
  "Evista",
  "Evkeeza",
  "Evolocumab",
  "Evusheld",
  "Excedrin",
  "Exemestane",
  "Ezetimibe",
  "Famotidine",
  "Farxiga",
  "Fasenra",
  "Faslodex",
  "Febuxostat",
  "Felodipine",
  "Femara",
  "Fenofibrate",
  "Fentanyl",
  "FeroSul",
  "Ferrous gluconate",
  "Ferrous Sulfate",
  "Fexofenadine",
  "Finasteride",
  "Fintepla",
  "Fioricet",
  "Firazyr",
  "Firmagon",
  "Fish Oil",
  "Flagyl",
  "Flecainide",
  "Flexeril",
  "Flomax",
  "Flonase",
  "Flonase Allergy Relief",
  "Florastor",
  "Flovent",
  "Flovent HFA",
  "Fluconazole",
  "Fludrocortisone",
  "FluMist Vaccine",
  "Fluocinonide",
  "Fluorouracil",
  "Fluoxetine",
  "Fluphenazine",
  "Flutamide",
  "Fluticasone",
  "Fluticasone and salmeterol",
  "Fluticasone nasal",
  "Fluvoxamine",
  "Focalin",
  "Folic Acid",
  "Formoterol",
  "Forteo",
  "Fosamax",
  "Fosfomycin",
  "Fulvestrant",
  "Furosemide",
  "Fycompa",
  "Gabapentin",
  "Galantamine",
  "Ganciclovir",
  "Garlic",
  "Gas-X",
  "Gatifloxacin",
  "GaviLyte G",
  "Gaviscon",
  "Gavreto",
  "Gazyva",
  "Gemcitabine",
  "Gemfibrozil",
  "Gemtesa",
  "Genotropin",
  "Gentamicin",
  "Gentamicin ophthalmic",
  "Genvoya",
  "Geodon",
  "Giazo",
  "Gilenya",
  "Ginger",
  "Ginkgo Biloba",
  "Ginseng",
  "Gleevec",
  "Glimepiride",
  "Glipizide",
  "Glipizide and metformin",
  "Glucagon",
  "Glucophage",
  "Glucosamine",
  "Glucotrol",
  "Glucovance",
  "Glutathione",
  "Glyburide",
  "Glycerin",
  "Glycopyrrolate",
  "Glyxambi",
  "Gocovri",
  "GoLYTELY",
  "Goserelin",
  "Granisetron",
  "Griseofulvin",
  "Guaifenesin",
  "Guanfacine",
  "Gvoke HypoPen",
  "Haegarda",
  "Halcion",
  "Haldol",
  "Halobetasol",
  "Haloperidol",
  "Harvoni",
  "Hawthorn",
  "Hemgenix",
  "Heparin",
  "Hepatitis B adult vaccine",
  "Herceptin",
  "Hibiclens",
  "Hiprex",
  "Histrelin",
  "Hizentra",
  "Horizant",
  "Humalog",
  "Humira",
  "Humulin 70/30",
  "Humulin N",
  "Humulin R",
  "Humulin RU 500",
  "Hydralazine",
  "Hydrea",
  "Hydrochlorothiazide",
  "Hydrochlorothiazide and irbesartan",
  "Hydrochlorothiazide and lisinopril",
  "Hydrochlorothiazide and losartan",
  "Hydrochlorothiazide and olmesartan",
  "Hydrochlorothiazide and triamterene",
  "Hydrochlorothiazide and valsartan",
  "Hydrocodone",
  "Hydrocodone and Acetaminophen",
  "Hydrocodone and ibuprofen",
  "Hydrocortisone",
  "Hydrocortisone topical",
  "Hydromorphone",
  "Hydroxychloroquine",
  "Hydroxyurea",
  "Hydroxyzine",
  "Hydroxyzine Pamoate",
  "Hyoscyamine",
  "Hytrin",
  "Hyzaar",
  "Ibandronate",
  "Ibrance",
  "Ibrutinib",
  "Ibu",
  "Ibuprofen",
  "Iclusig",
  "Icosapent",
  "Idhifa",
  "Ilumya",
  "Imatinib",
  "Imbruvica",
  "Imdur",
  "Imfinzi",
  "Imipramine",
  "Imitrex",
  "Imodium",
  "Imodium A-D",
  "Impoyz",
  "Imuran",
  "Inbrija",
  "Incruse Ellipta",
  "Indapamide",
  "Inderal",
  "Indocin",
  "Indomethacin",
  "Inflectra",
  "Infliximab",
  "Ingrezza",
  "Injectafer",
  "Inlyta",
  "Insulin Aspart",
  "Insulin Detemir",
  "Insulin Glargine",
  "Insulin Lispro",
  "Insulin Regular",
  "Intuniv",
  "Invega",
  "Invega Sustenna",
  "Invokana",
  "Iopamidol",
  "Ipratropium",
  "Irbesartan",
  "Isoniazid",
  "Isosorbide",
  "Isosorbide dinitrate",
  "Isosorbide mononitrate",
  "Isotretinoin",
  "Itraconazole",
  "Ivabradine",
  "Ivermectin",
  "Jadenu",
  "Jaimiess",
  "Jakafi",
  "Jalyn",
  "Jantoven",
  "Janumet",
  "Janumet XR",
  "Januvia",
  "Jardiance",
  "Jasmiel",
  "Jatenzo",
  "Javygtor",
  "Jaypirca",
  "Jelmyto",
  "Jemperli",
  "Jencycla",
  "Jentadueto",
  "Jentadueto XR",
  "Jesduvroq",
  "Jevtana",
  "Jinteli",
  "Joenja",
  "Jolessa",
  "Jornay PM",
  "Jublia",
  "Juluca",
  "Junel",
  "Junel 1.5/30",
  "Junel 1/20",
  "Junel Fe 24",
  "Juniper",
  "Juvederm",
  "Jynarque",
  "Jynneos",
  "K-Dur",
  "Kadcyla",
  "kalbitor",
  "Kalydeco",
  "Kanamycin",
  "Kaopectate",
  "Kapvay",
  "Kava",
  "Kayexalate",
  "Keflex",
  "Kenalog",
  "Kenalog-40",
  "Keppra",
  "Keppra XR",
  "Kerendia",
  "Kesimpta",
  "Ketalar",
  "Ketamine",
  "Ketoconazole",
  "Ketoconazole Shampoo",
  "Ketoconazole topical",
  "Ketoprofen",
  "Ketorolac",
  "Ketorolac ophthalmic",
  "Ketorolac Tromethamine",
  "Ketotifen",
  "Ketotifen ophthalmic",
  "Kevzara",
  "Keytruda",
  "Kineret",
  "Kisqali",
  "Klisyri",
  "Klonopin",
  "Klor-Con",
  "Kombiglyze XR",
  "Konvomep",
  "Korlym",
  "Kratom",
  "Krill Oil",
  "Kyleena",
  "Kynmobi",
  "Kyprolis",
  "Labetalol",
  "Lacosamide",
  "Lactulose",
  "Lamictal",
  "Lamotrigine",
  "Lanadelumab",
  "Lansoprazole",
  "Lantus",
  "Lasix",
  "Latanoprost",
  "Latuda",
  "Leflunomide",
  "Lenvatinib",
  "Lenvima",
  "Leqvio",
  "Letrozole",
  "Leukeran",
  "Leuprolide",
  "Levaquin",
  "Levemir",
  "Levetiracetam",
  "Levocetirizine",
  "Levodopa",
  "Levofloxacin",
  "Levonorgestrel",
  "Levothyroxine",
  "Lexapro",
  "Lexette",
  "Lialda",
  "Lidex",
  "Lidocaine",
  "Lidocaine viscous",
  "Liletta",
  "Linezolid",
  "Linzess",
  "Liothyronine",
  "Lipitor",
  "Lisdexamfetamine",
  "Lisinopril",
  "Lithium",
  "Loestrin 24 Fe",
  "Lofexidine",
  "Lokelma",
  "Lomotil",
  "Loperamide",
  "Lopressor",
  "Loratadine",
  "Lorazepam",
  "Lorlatinib",
  "Losartan",
  "Lovastatin",
  "Lovenox",
  "Lunesta",
  "Lupron Depot",
  "Lurasidone",
  "Luxiq",
  "Lyrica",
  "Lyumjev",
  "Macrobid",
  "Magnesium oxide",
  "Magnesium sulfate",
  "Mavenclad",
  "Mavyret",
  "Mayzent",
  "Meclizine",
  "Medrol",
  "Medrol Dosepak",
  "Melatonin",
  "Meloxicam",
  "Memantine",
  "Meropenem",
  "Mesalamine",
  "Metamucil",
  "Metformin",
  "Methadone",
  "Methimazole",
  "Methocarbamol",
  "Methotrexate",
  "Methylphenidate",
  "Methylprednisolone",
  "Metoclopramide",
  "Metoprolol",
  "Metronidazole",
  "Midazolam",
  "Midodrine",
  "Minoxidil",
  "MiraLAX",
  "Mirtazapine",
  "Misoprostol",
  "Mobic",
  "Modafinil",
  "Mometasone",
  "Montelukast",
  "Morphine",
  "Motrin",
  "Mounjaro",
  "Mucinex",
  "Mupirocin",
  "Mupirocin topical",
  "Mycapssa",
  "Mycophenolate mofetil",
  "Myfembree",
  "Mylotarg",
  "Myrbetriq",
  "Nabumetone",
  "NAC",
  "Nadolol",
  "Naloxone",
  "Naltrexone",
  "Namenda",
  "Naprosyn",
  "Naproxen",
  "Naratriptan",
  "Narcan",
  "Nasacort",
  "Nayzilam",
  "Nebivolol",
  "Neomycin",
  "Neosporin",
  "Nerlynx",
  "Neupro",
  "Neurontin",
  "Nexium",
  "Nexletol",
  "Nexlizet",
  "Nexplanon",
  "Niacin",
  "Nicardipine",
  "Nicotine",
  "Nifedipine",
  "Nilandron",
  "Nilutamide",
  "Ninlaro",
  "Nirmatrelvir and ritonavir",
  "Nitrofurantoin",
  "Nitroglycerin",
  "Nitrostat",
  "Nitrous Oxide",
  "Nivolumab",
  "Norco",
  "Norepinephrine",
  "Norethindrone",
  "Norflex",
  "Nortriptyline",
  "Norvasc",
  "Nourianz",
  "NovoLog",
  "NP Thyroid",
  "NPlate",
  "Nubeqa",
  "Nucynta",
  "Nurtec ODT",
  "Nystatin",
  "Nystatin topical",
  "Ocrevus",
  "Octreotide",
  "Ofev",
  "Ofloxacin",
  "Ofloxacin ophthalmic",
  "Ofloxacin otic",
  "Olanzapine",
  "Olaparib",
  "Olmesartan",
  "Olopatadine nasal",
  "Olopatadine ophthalmic",
  "Olux",
  "Omalizumab",
  "Omega-3",
  "Omega-3 Fish Oil",
  "Omeprazole",
  "Omnicef",
  "Ondansetron",
  "Onfi",
  "Ongentys",
  "Onglyza",
  "Onpattro",
  "Onureg",
  "Opdivo",
  "Opzelura",
  "Orencia",
  "Orgovyx",
  "Oriahnn",
  "Orladeyo",
  "Orlistat",
  "Orphenadrine",
  "Ortho Tri-Cyclen",
  "Oseltamivir",
  "Osimertinib",
  "Otezla",
  "Oxaliplatin",
  "Oxandrolone",
  "Oxazepam",
  "Oxcarbazepine",
  "Oxtella XR",
  "Oxybutynin",
  "Oxycodone",
  "Oxycontin",
  "Oxygen",
  "Oxymetazoline",
  "Oxymetazoline nasal",
  "Oxytocin",
  "Ozanimod",
  "Ozempic",
  "Paclitaxel",
  "Pantoprazole",
  "Paracetamol",
  "Paragard",
  "Paroxetine",
  "Paxil",
  "Paxlovid",
  "Pentasa",
  "Pepcid",
  "Percocet",
  "Phenazopyridine",
  "Phenergan",
  "Phenobarbital",
  "Phentermine",
  "Phenylephrine",
  "Phenytoin",
  "Phexxi",
  "Pioglitazone",
  "Plan B",
  "Plaquenil",
  "Plavix",
  "Polyethylene glycol 3350",
  "Potassium Chloride",
  "Pradaxa",
  "Praluent",
  "Pramipexole",
  "Pravastatin",
  "Prazosin",
  "Prednisolo",
  "Prednisone",
  "Pregabalin",
  "Premarin",
  "Prilosec",
  "Primidone",
  "Pristiq",
  "ProAir HFA",
  "Probuphine",
  "Prochlorperazine",
  "Progesterone",
  "Prolia",
  "Promacta",
  "Promethazine",
  "Propranolol",
  "Protonix",
  "Provenge",
  "Prozac",
  "Pseudoephedrine",
  "Pyridium",
  "Qbrelis",
  "Qbrexza",
  "Qdolo",
  "Qelbree",
  "Qlosi",
  "QNASL",
  "Qsymia",
  "Qtern",
  "Qualaquin",
  "Quartette",
  "Quassia",
  "Quazepam",
  "Qudexy XR",
  "Quelicin",
  "Quercetin",
  "Questran",
  "Quetiapine",
  "QuilliChew ER",
  "Quillivant XR",
  "Quinapril",
  "Quinidine",
  "Quinine",
  "Quizartinib",
  "Qulipta",
  "Qutenza",
  "Quviviq",
  "Qvar",
  "Qvar Redihaler",
  "Rabeprazole",
  "Raloxifene",
  "Ramelteon",
  "Ramipril",
  "Ranexa",
  "Ranitidine",
  "Ranolazine",
  "Rapamune",
  "Reclast",
  "Reglan",
  "Relafen",
  "Relugolix",
  "Remdesivir",
  "Remeron",
  "Remicade",
  "Renflexis",
  "Renvela",
  "Repaglinide",
  "Repatha",
  "Requip",
  "Restasis",
  "Restoril",
  "Retevmo",
  "Revlimid",
  "Rexulti",
  "Reyvow",
  "Rifampin",
  "Rifaximin",
  "Rinvoq",
  "Risdiplam",
  "Risedronate",
  "Risperdal",
  "Risperidone",
  "Ritalin",
  "Rituxan",
  "Rituxan Hycela",
  "Rituximab",
  "Rivaroxaban",
  "Rivastigmine",
  "Rizatriptan",
  "Robaxin",
  "Robitussin",
  "Rocephin",
  "Roflumilast",
  "Ropinirole",
  "Rosuvastatin",
  "Rowasa",
  "Ruconest",
  "Rybelsus",
  "Rydapt",
  "Rytary",
  "Sabril",
  "Sacubitril and valsartan",
  "Salbutamol",
  "Salmeterol",
  "Sandostatin",
  "Saphnelo",
  "Saxenda",
  "Scopolamine",
  "secukinumab",
  "Semaglutide",
  "Senna",
  "Senokot",
  "Sernivo",
  "Seroquel",
  "Sertraline",
  "Sevelamer",
  "Shingrix",
  "Sildenafil",
  "Simethicone",
  "Simponi",
  "Simvastatin",
  "Sinemet",
  "Singulair",
  "Sitagliptin",
  "Skyrizi",
  "Sodium bicarbonate",
  "Sodium Chloride",
  "Sofosbuvir",
  "Solifenacin",
  "Soliqua",
  "Soliris",
  "SoluMEDROL",
  "Soma",
  "Somatuline Depot",
  "Somavert",
  "Sotalol",
  "Sovaldi",
  "Spinraza",
  "Spiriva",
  "Spiriva Respimat",
  "Spironolactone",
  "Sprycel",
  "Stelara",
  "Strattera",
  "Stribild",
  "Sublocade",
  "Suboxone",
  "Sucralfate",
  "Sudafed",
  "Sulfamethoxazole and trimethoprim",
  "Sulfasalazine",
  "Sumatriptan",
  "Supprelin LA",
  "Sutent",
  "Symbicort",
  "Sympazan",
  "Synjardy",
  "Synthroid",
  "Tacrolimus",
  "Tadalafil",
  "Takhzyro",
  "Taltz",
  "Tamiflu",
  "Tamoxifen",
  "Tamsulosin",
  "Tazarotene",
  "Tazorac",
  "Tecartus",
  "Tecentriq",
  "Tecvayli",
  "Tegretol",
  "Telmisartan",
  "Temazepam",
  "Temovate",
  "Tepezza",
  "Terazosin",
  "Terbinafine",
  "Tessalon Perles",
  "Testosterone",
  "Tetracycline",
  "Theophylline",
  "Thiamine",
  "Tibsovo",
  "Timolol",
  "Tirzepatide",
  "Tizanidine",
  "Tobramycin",
  "Tolterodine",
  "Topamax",
  "Topiramate",
  "Toprol XL",
  "Toradol",
  "Torsemide",
  "Toujeo",
  "Tradjenta",
  "Tramadol",
  "Tranexamic acid",
  "Trazodone",
  "Treanda",
  "Trelegy Ellipta",
  "Trelstar",
  "Tremfya",
  "Tresiba",
  "Tretinoin",
  "Triamcinolone",
  "Triamterene",
  "Trileptal",
  "Trimethoprim",
  "Trintellix",
  "Triptorelin",
  "Triumeq",
  "Trokendi XR",
  "Trulicity",
  "Truxima",
  "Twirla",
  "Tylenol",
  "Tysabri",
  "Ubiquinone",
  "Ubrelvy",
  "Ubrogepant",
  "Uceris",
  "Udenyca",
  "Ulipristal",
  "Uloric",
  "Ultiva",
  "Ultomiris",
  "Ultracet",
  "Ultram",
  "Ultravate",
  "Ultravist",
  "Umeclidinium",
  "Umeclidinium and vilanterol",
  "Unasyn",
  "Unisom",
  "Unisom Sleep Gels",
  "Unithroid",
  "Upadacitinib",
  "Uplizna",
  "Upneeq",
  "Uptravi",
  "Urea",
  "Urea Cream",
  "Urecholine",
  "Uretron D/S",
  "Uribel",
  "Urispas",
  "Uristat",
  "Uro-Mag",
  "Uro-MP",
  "Urocit-K",
  "Urogesic-Blue",
  "Urokinase",
  "Uroxatral",
  "Urso",
  "Ursodiol",
  "Ustekinumab",
  "Uzedy",
  "Valacyclovir",
  "Valium",
  "Valproate Sodium",
  "Valproic acid",
  "Valsartan",
  "Valtoco",
  "Valtrex",
  "Vancomycin",
  "Vanos",
  "Varenicline",
  "Vascepa",
  "Vasotec",
  "Velcade",
  "Venclexta",
  "Venlafaxine",
  "Venofer",
  "Ventolin",
  "Ventolin HFA",
  "Veozah",
  "Verapamil",
  "Versed",
  "Verzenio",
  "VESIcare",
  "Viagra",
  "Vibramycin",
  "Vicodin",
  "Victoza",
  "Viibryd",
  "Vilazodone",
  "Vimpat",
  "Vincristine",
  "Vistaril",
  "Vitamin A",
  "Vitamin B12",
  "Vitamin C",
  "Vitamin D",
  "Vitamin D3",
  "Vitamin E",
  "Vivitrol",
  "Voltaren",
  "Voltaren Arthritis Pain Gel",
  "Voriconazole",
  "Vortioxetine",
  "Vosevi",
  "Votrient",
  "Vraylar",
  "Vyepti",
  "Vyndamax",
  "Vyvanse",
  "Wakix",
  "Wal-itin",
  "Warfarin",
  "Wegovy",
  "Welchol",
  "Welireg",
  "Wellbutrin",
  "Wellbutrin SR",
  "Wellbutrin XL",
  "Westcort",
  "Wezlana",
  "Wilate",
  "Wild yam",
  "Willow Bark",
  "Winlevi",
  "Witch Hazel",
  "Witch hazel topical",
  "Wixela Inhub",
  "Wormwood",
  "Wynzora",
  "Xadago",
  "Xalatan",
  "Xalkori",
  "Xanax",
  "Xanax XR",
  "Xarelto",
  "Xcopri",
  "Xdemvy",
  "Xeljanz",
  "Xeloda",
  "Xelstrym",
  "Xembify",
  "Xenical",
  "Xenleta",
  "Xeomin",
  "Xermelo",
  "Xgeva",
  "Xhance",
  "Xiaflex",
  "Xifaxan",
  "Xigduo XR",
  "Xiidra",
  "Xofigo",
  "Xofluza",
  "Xolair",
  "Xopenex",
  "Xopenex HFA",
  "Xospata",
  "Xphozah",
  "Xpovio",
  "Xtampza ER",
  "Xtandi",
  "Xulane",
  "Xultophy",
  "Xylitol",
  "Xylocaine",
  "Xylocaine Jelly",
  "Xyosted",
  "Xyrem",
  "Xywav",
  "Xyzal",
  "Yasmin",
  "Yaz",
  "Ycanth",
  "Yellow fever vaccine",
  "Yervoy",
  "Yescarta",
  "Yohimbe",
  "Yohimbine",
  "Yondelis",
  "Yuflyma",
  "Yupelri",
  "Yusimry",
  "Yuvafem",
  "Zaditor",
  "Zafirlukast",
  "Zaleplon",
  "Zanaflex",
  "Zantac",
  "Zarxio",
  "Zebeta",
  "Zegalogue",
  "Zenpep",
  "Zepbound",
  "Zeposia",
  "Zestril",
  "Zetia",
  "Zidovudine",
  "Zinc",
  "Zinc gluconate",
  "Zinc sulfate",
  "Ziprasidone",
  "Zithromax",
  "Zocor",
  "Zofran",
  "Zofran ODT",
  "Zoladex",
  "Zoledronic acid",
  "Zolmitriptan",
  "Zoloft",
  "Zolpidem",
  "Zometa",
  "Zomig",
  "Zonegran",
  "Zonisamide",
  "Zopiclone",
  "Zosyn",
  "Zovirax",
  "Zydelig",
  "Zykadia",
  "Zyloprim",
  "Zynteglo",
  "Zyprexa",
  "Zyrtec",
  "Zytiga",
  "Zyvox",
  "ZzzQuil",
  "1-Day",
  "12 Hour Cold Maximum Strength",
  "12 Hour Nasal",
  "12 Hour Nasal Decongestant",
  "13c urea and citric acid",
  "14c urea",
  "2 in 1 Dandruff",
  "3M Skin and Nasal Antiseptic",
  "4 Way Saline nasal",
  "4-Way",
  "4-Way Long Lasting",
  "4-Way Menthol",
  "5-HTP",
  "5-HTP Mood and Stress",
  "5-hydroxytryptophan",
  "5-hydroxytryptophan, melatonin, and pyridoxine",
  "60 Second Fluoride Gel",
  "60-Second Fluoride Foam",
  "7T Gummy ES Chewable Tablets",
  "8-Mop",
];

const medicationTrie = buildTrie(medicationList);
export default medicationTrie;
