const results = [
  {
    drugBrand: "Drug 1",
    genericName: "Aceto",
    activeIngredients: "baclofen",
    uses: "cures the plague",
    manufacturers: "Johnson & Johnson",
    marketingStatus: "Discontinued",
    strength: "0.75MG/0.5ML",
  },
  {
    drugBrand: "Drug 2",
    genericName: "Acetoman",
    activeIngredients: "klor-con",
    uses: "cures the plague",
    manufacturers: "CVS",
    marketingStatus: "In Stock",
    strength: "0.75MG/0.5ML",
  },
  {
    drugBrand: "Drug 3",
    genericName: "Acetoman2",
    activeIngredients: "Acetomenaphin",
    uses: "cures the plague",
    manufacturers: "CVSII",
    marketingStatus: "In Stock",
    strength: "0.75MG/0.5ML",
  },
  {
    drugBrand: "Drug 4",
    genericName: "Asetoman",
    activeIngredients: "Acetomenaphin",
    uses: "cures the plague",
    manufacturers: "Drugs R Us",
    marketingStatus: "In Stock",
    strength: "0.75MG/0.5ML",
  },
  {
    drugBrand: "Drug 5",
    genericName: "Acetoman2",
    activeIngredients: "Acetomenaphin",
    uses: "cures the plague",
    manufacturers: "Free Drugs",
    marketingStatus: "In Stock",
    strength: "0.75MG/0.5ML",
  },
  {
    drugBrand: "Drug 6",
    genericName: "Asetoman",
    activeIngredients: "Acetomenaphin",
    uses: "cures the plague",
    manufacturers: "Drugs R Us",
    marketingStatus: "In Stock",
    strength: "0.75MG/0.5ML",
  },
  {
    drugBrand: "Drug 7",
    genericName: "Acetoman2",
    activeIngredients: "Acetomenaphin",
    uses: "cures the plague",
    manufacturers: "Free Drugs",
    marketingStatus: "In Stock",
    strength: "0.75MG/0.5ML",
  },
  {
    drugBrand: "Drug 8",
    genericName: "Asetoman",
    activeIngredients: "Acetomenaphin",
    uses: "cures the plague",
    manufacturers: "Drugs R Us",
    marketingStatus: "In Stock",
    strength: "0.75MG/0.5ML",
  },
  {
    drugBrand: "Drug ",
    genericName: "Acetoman2",
    activeIngredients: "Acetomenaphin",
    uses: "cures the plague",
    manufacturers: "Free Drugs",
    marketingStatus: "In Stock",
    strength: "0.75MG/0.5ML",
  },
];

export {results}